<a href="https://colab.research.google.com/github/JavZon/Machine_Learning/blob/main/Ordinal_Encoder_OneHotEncoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
URL ="https://github.com/ageron/handson-ml2/blob/master/datasets/housing/housing.csv?raw=true"
df = pd.read_csv(URL)
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [3]:
bins=[0,1.5, 3.0, 4.5, 6.0, np.inf]
labels=[1,2,3,4,5]
df['income_cat']=pd.cut(df['median_income'], bins=bins, labels=labels)
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  \
0       322.0       126.0         8.3252            452600.0        NEAR BAY   
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY   
2       496.0       177.0         7.2574            352100.0        NEAR BAY   
3       558.0       219.0         5.6431            341300.0        NEAR BAY   
4       565.0       259.0         3.8462            342200.0        NEAR BAY   

  income_cat  
0          5  
1          5  
2          5  
3          4  
4          3

In [4]:
df['income_cat'].value_counts()

income_cat
3    7236
2    6581
4    3639
5    2362
1     822
Name: count, dtype: int64

In [5]:
from sklearn.model_selection import StratifiedShuffleSplit
sss=StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=45)

for train_index, test_index in sss.split(df, df['income_cat']):
  train_set=df.loc[train_index]
  test_set=df.loc[train_index]

In [6]:
train_set.sample(3)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
5285     -118.46     34.05                25.0       4077.0          1151.0   
18409    -121.82     37.27                16.0       2030.0           321.0   
8303     -118.12     33.76                43.0       3070.0           668.0   

       population  households  median_income  median_house_value  \
5285       1719.0      1017.0         3.7721            337500.0   
18409      1343.0       365.0         6.3566            279100.0   
8303       1240.0       646.0         3.7813            461500.0   

      ocean_proximity income_cat  
5285        <1H OCEAN          3  
18409       <1H OCEAN          5  
8303       NEAR OCEAN          3

In [7]:
df.drop(columns='income_cat', inplace=True)

In [8]:
train_set.drop(columns='income_cat', inplace=True)
test_set.drop(columns='income_cat', inplace=True)

In [9]:
housing=train_set.copy()
housing_labels=train_set['median_house_value'].copy()
train_set.drop(columns='median_house_value', inplace=True)

In [ ]:
housing2=housing.drop(columns='ocean_proximity')
housing2

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16908    -122.37     37.58                34.0       2697.0           313.0   
634      -122.16     37.71                37.0       1507.0           242.0   
10909    -117.86     33.74                32.0        691.0           151.0   
3736     -118.40     34.18                32.0       3724.0           899.0   
14749    -117.05     32.57                22.0       2857.0           516.0   
...          ...       ...                 ...          ...             ...   
1249     -122.09     39.13                28.0       4169.0           895.0   
1941     -120.97     38.65                 9.0       3707.0           602.0   
955      -121.93     37.66                24.0       3166.0           424.0   
6107     -117.90     34.11                37.0       1286.0           255.0   
12098    -117.34     33.96                15.0       6437.0          1298.0   

       population  households  median_income  median_house_value  
16908       810.0       279.0        12.4291            500001.0  
634         632.0       253.0         4.5553            191000.0  
10909       926.0       148.0         4.1250            175900.0  
3736       1912.0       791.0         3.5711            312700.0  
14749      2412.0       496.0         4.7337            127600.0  
...           ...         ...            ...                 ...  
1249       2587.0       810.0         2.3310             65500.0  
1941       1601.0       555.0         4.0714            300600.0  
955        1081.0       400.0         8.3337            500001.0  
6107       1047.0       249.0         4.2019            140100.0  
12098      2805.0      1205.0         4.1883            184500.0  

[16512 rows x 9 columns]

In [ ]:
housing2.corr()

longitude  latitude  housing_median_age  total_rooms  \
longitude            1.000000 -0.924991           -0.104731     0.046229   
latitude            -0.924991  1.000000            0.009273    -0.037930   
housing_median_age  -0.104731  0.009273            1.000000    -0.360118   
total_rooms          0.046229 -0.037930           -0.360118     1.000000   
total_bedrooms       0.069228 -0.067314           -0.318354     0.930789   
population           0.098784 -0.108873           -0.293744     0.851353   
households           0.054957 -0.071532           -0.300781     0.918175   
median_income       -0.012543 -0.082782           -0.118303     0.199337   
median_house_value  -0.042491 -0.146351            0.107314     0.134346   

                    total_bedrooms  population  households  median_income  \
longitude                 0.069228    0.098784    0.054957      -0.012543   
latitude                 -0.067314   -0.108873   -0.071532      -0.082782   
housing_median_age       -0.318354   -0.293744   -0.300781      -0.118303   
total_rooms               0.930789    0.851353    0.918175       0.199337   
total_bedrooms            1.000000    0.872504    0.978963      -0.007481   
population                0.872504    1.000000    0.902875       0.004977   
households                0.978963    0.902875    1.000000       0.014372   
median_income            -0.007481    0.004977    0.014372       1.000000   
median_house_value        0.051329   -0.024739    0.067504       0.688185   

                    median_house_value  
longitude                    -0.042491  
latitude                     -0.146351  
housing_median_age            0.107314  
total_rooms                   0.134346  
total_bedrooms                0.051329  
population                   -0.024739  
households                    0.067504  
median_income                 0.688185  
median_house_value            1.000000

In [ ]:
housing2.corrwith(housing2['median_house_value']).sort_values(ascending=False)

median_house_value    1.000000
median_income         0.688185
total_rooms           0.134346
housing_median_age    0.107314
households            0.067504
total_bedrooms        0.051329
population           -0.024739
longitude            -0.042491
latitude             -0.146351
dtype: float64

In [ ]:
housing2.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        169
population              0
households              0
median_income           0
median_house_value      0
dtype: int64

In [10]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(strategy='median')

In [11]:
housing.head(2)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16908    -122.37     37.58                34.0       2697.0           313.0   
634      -122.16     37.71                37.0       1507.0           242.0   

       population  households  median_income  median_house_value  \
16908       810.0       279.0        12.4291            500001.0   
634         632.0       253.0         4.5553            191000.0   

      ocean_proximity  
16908      NEAR OCEAN  
634          NEAR BAY

In [12]:
housing.drop(columns='median_house_value', inplace=True)

In [15]:
housing.head(2)
housing2=housing.drop(columns='ocean_proximity')
housing2.sample(2)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
2386     -119.49     37.10                24.0       2532.0           555.0   
14593    -117.18     32.83                27.0       2346.0           399.0   

       population  households  median_income  
2386       1564.0       507.0         2.3359  
14593      1105.0       373.0         4.2708

In [16]:
imputer.fit(housing2)
imputer.statistics_

array([-118.49  ,   34.25  ,   29.    , 2127.    ,  433.    , 1166.    ,
        409.    ,    3.5377])

In [17]:
X=imputer.transform(housing2)
x=imputer.fit_transform(housing2)

In [18]:
x

array([[-122.37  ,   37.58  ,   34.    , ...,  810.    ,  279.    ,
          12.4291],
       [-122.16  ,   37.71  ,   37.    , ...,  632.    ,  253.    ,
           4.5553],
       [-117.86  ,   33.74  ,   32.    , ...,  926.    ,  148.    ,
           4.125 ],
       ...,
       [-121.93  ,   37.66  ,   24.    , ..., 1081.    ,  400.    ,
           8.3337],
       [-117.9   ,   34.11  ,   37.    , ..., 1047.    ,  249.    ,
           4.2019],
       [-117.34  ,   33.96  ,   15.    , ..., 2805.    , 1205.    ,
           4.1883]])

In [19]:
new_housing=pd.DataFrame(x, columns=housing2.columns, index=housing2.index)
new_housing.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
dtype: int64

In [20]:
housing2.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16908    -122.37     37.58                34.0       2697.0           313.0   
634      -122.16     37.71                37.0       1507.0           242.0   
10909    -117.86     33.74                32.0        691.0           151.0   
3736     -118.40     34.18                32.0       3724.0           899.0   
14749    -117.05     32.57                22.0       2857.0           516.0   

       population  households  median_income  
16908       810.0       279.0        12.4291  
634         632.0       253.0         4.5553  
10909       926.0       148.0         4.1250  
3736       1912.0       791.0         3.5711  
14749      2412.0       496.0         4.7337

In [21]:
new_housing['ocean_proximity']=train_set['ocean_proximity'].copy()
new_housing.head(2)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16908    -122.37     37.58                34.0       2697.0           313.0   
634      -122.16     37.71                37.0       1507.0           242.0   

       population  households  median_income ocean_proximity  
16908       810.0       279.0        12.4291      NEAR OCEAN  
634         632.0       253.0         4.5553        NEAR BAY

OrdinalEncoder
Turli categorylardagi matnlarni son ko'rinishiga o'tkazadi





In [4]:

from sklearn.preprocessing import OrdinalEncoder

# Bu modul categorylarni songa ajratib beradi.
#housing_cat=new_housing[['ocean_proximity']]

# Bizning dfdagi matnlarni songa o'tkazib beradi
ordinal_encoder=OrdinalEncoder()

In [5]:
data={'A':[23,1,8,72,13,66,45,14],
      'B':['Red', 'Black','Black','Red','Green','Red','Black','Green']}
color_df=pd.DataFrame(data)
color_df

A      B
0  23    Red
1   1  Black
2   8  Black
3  72    Red
4  13  Green
5  66    Red
6  45  Black
7  14  Green

In [6]:
new_color=ordinal_encoder.fit_transform(color_df[['B']]) # bu metodning ichiga df kiritilishi kerak Series emas
# shuning uchun color_df[['B']] quyidagicha df holatiga keltirib olamiz

In [7]:
new_color

array([[2.],
       [0.],
       [0.],
       [2.],
       [1.],
       [2.],
       [0.],
       [1.]])

In [8]:
color_df['C']=new_color


**Lekin bu usulning kamchiligi** - sonlar qancha bir biriga yaqin bo'lsa algoritm ularni shunchalik bir biriga yaqin deb o'ylaydi. Bizning misolda Black - 0, Green - 1, Red - 2 bo'ldi. Algoritm esa 0 soni 1 ga yaqin bo'lgani uchun Black ni Greenga yaqin orasida bog'liqlik bor deb o'ylaydi. Lekin haqiqatda esa bu xato. Bular shunchaki ranglar va ularning bir biri bilan hech qanday aloqasi yo'q. Bu metodning kamchiligi shunda.

In [9]:
color_df

A      B    C
0  23    Red  2.0
1   1  Black  0.0
2   8  Black  0.0
3  72    Red  2.0
4  13  Green  1.0
5  66    Red  2.0
6  45  Black  0.0
7  14  Green  1.0

**OneHotEncoder**


Bu ham categoriyalarni son ko'rinishiga olib o'tadi. Array qaytaradi.Lekin necha xil category bo'lsa o'shancha ustun qaytarib, mos keluvchi ustunga 1, qolganlariga 0 qo'yadi.

In [11]:
color_df

A      B    C
0  23    Red  2.0
1   1  Black  0.0
2   8  Black  0.0
3  72    Red  2.0
4  13  Green  1.0
5  66    Red  2.0
6  45  Black  0.0
7  14  Green  1.0

In [12]:
from sklearn.preprocessing import OneHotEncoder

one_encoder=OneHotEncoder()
# Bu metodga ham 2d array kiritilishi lozim

one_hot=one_encoder.fit_transform(color_df[['B']])

# Keyin esa bu qaytgan javobni toarray() orqali arrayga o'tkazib olamiz va yana qayta dfga o'tkazamiz

In [16]:
abc=one_hot.toarray()
abc

array([[0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [14]:
color_df[['Black','Green','Red']]=abc  # endi bu arrayni dfning davomiga qo'shib qo'yamiz

In [17]:
color_df

A      B    C  Black  Green  Red
0  23    Red  2.0    0.0    0.0  1.0
1   1  Black  0.0    1.0    0.0  0.0
2   8  Black  0.0    1.0    0.0  0.0
3  72    Red  2.0    0.0    0.0  1.0
4  13  Green  1.0    0.0    1.0  0.0
5  66    Red  2.0    0.0    0.0  1.0
6  45  Black  0.0    1.0    0.0  0.0
7  14  Green  1.0    0.0    1.0  0.0